### ISSUE TITLE
Docker secrets

### ISSUE THREAD

**Issue by SylverRat** [erikdubbelboer/phpRedisAdmin#185]
Any ideas how to use docker secrets with this?
This does not work for me:
```
secrets:
  redis_password:
    file: $DOCKER/secrets/redis_password

services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    command: ["bash", "-c", 'docker-entrypoint.sh --requirepass "$$(cat $$REDIS_PASSWORD_FILE)"']
    secrets:
      - redis_password
    volumes:
      - $DOCKER/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - $DOCKER/redis/data:/data
    environment:
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    container_name: phpredisadmin
    hostname: phpredisadmin
    restart: unless-stopped
    depends_on:
      - redis
    secrets:
      - redis_password
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_AUTH_FILE=/run/secrets/redis_password
```
TIA,
