### ISSUE TITLE
Show number of keys without explicitly displaying them

### ISSUE THREAD

**Issue by andrey-helldar** [erikdubbelboer/phpRedisAdmin#199]
I'm using the Docker version of the admin panel and ran into a problem that in the select of the database selection it shows the number of keys, despite the fact that they are not in the general list below. I leave this instruction for those who will face the same problem and, like me, will not be able to find the answer in the project repository on GitHub.

1. You need to copy the [`config.sample.inc.php`](https://github.com/erikdubbelboer/phpRedisAdmin/blob/master/includes/config.sample.inc.php) file and then write the mapping in docker-compose.yml:
2. Change the value of the `maxkeylen` key in it. I indicated 2048.
3. Adding file mapping:
```yaml
services:
    redis-webui:
        image: 'erikdubbelboer/phpredisadmin:latest'
        environment:
            - ADMIN_USER=${REDIS_WEBUI_USERNAME}
            - ADMIN_PASS=${REDIS_WEBUI_PASSWORD}
            - REDIS_1_HOST=${REDIS_WEBUI_CONNECT_HOST}
            - REDIS_1_PORT=${REDIS_WEBUI_CONNECT_PORT}
        volumes:
            - './redis/includes/config.sample.inc.php:/src/app/includes/config.sample.inc.php'
        ports:
            - "${REDIS_WEBUI_PORT}:80"
        networks:
            - sail
        depends_on:
            - redis
```

### Before
![image](https://user-images.githubusercontent.com/10347617/233376914-466b30cf-2d24-4a78-926c-3b1d128353dd.png)

### After
![image](https://user-images.githubusercontent.com/10347617/233379831-5253d86c-1cc5-40b8-9e0a-042daa4e69b8.png)
